### ISSUE TITLE
Expose info panel as camera

### ISSUE THREAD

**Issue by troygNZ** [troygNZ/homebridge-solax#2]
Work around Homekit info display, and show stuff in an info panel

**Comment by Ngawang67** [comment]
Hello TroygNZ,

I managed to get the info from the Solax using two network adapters and a reverse proxy. (No other option, unfortunately).
Homebridge is working fine with all my devices, except the Solax.
My problem is, I don't find any solution to show and use the Solax data in Homekit.  I tried light generic info , battery, with no luck. I'm sure it is possible, it is only numbers I need to display/use in scenarios.

Do you have an idea ? What did you do ?

**Comment by troygNZ** [comment]
Hi,
When you access the reverse proxy, do you get a JSON response when you navigate to http://<PROXY_HOST_OR_URL/>/api/realTimeData.htm where PROXY_HOST_OR_URL is your proxy's address?
It'll need to response with the JSON payload when the '/api/realTimeData.htm' is appended on the end.

It should hopefully give back a JSON response. If it does, are you happy to share the payload. If it doesn't, it may just be a case of tweaking your reverse proxy to handle that URL suffix, and route to the appropriate place on the other network.
