### ISSUE TITLE
Verbose mode

### ISSUE THREAD

**Issue by Cardo1** [troygNZ/homebridge-solax#24]
**Is your feature request related to a problem? Please describe.**
I like the values given to be reasonably up to date, with a little averaging to deal with wild fluctuations.  I’ve currently set the polling time to 10s.  The issue is the HB log has the polling strings shown every 10s, which is filling up the log quite considerably!

**Describe the solution you'd like**
A verbose option to enable or disable the regular polling strings.  With verbose logging on, this will show, with verbose off, only the get strings will show.

**Describe alternatives you've considered**
Putting up with it!

**Additional context**
N/A

Thanks!

**Comment by troygNZ** [comment]
Thanks @Cardo1 - are you able to send through a small snippet of the logs to confirm it's what I think it is.

I have it dump out every time the history buffer half-fills - in my case I have a reasonably large buffer, so only spits lots out every so often.

In interim I'll reduce the threshold to be debug level logging. The debug logging control in HomeBridge UI etc should provide the ability for more diagnostics.

**Comment by troygNZ** [comment]
On the assumption its the moving average log entries that are showing up and filling your logs, I've dropped their threshold to debug level. Once updated to version 1.3.1, please let me know if it's looking better. Or if not, please feel free to send through a snippet of the logs.

**Comment by Cardo1** [comment]
The logs are indeed now gone. 👍
