### ISSUE TITLE
Ability to change battery use times in inverter settings

### ISSUE THREAD

**Issue by Cardo1** [troygNZ/homebridge-solax#26]
**Is your feature request related to a problem? Please describe.**
I’m guessing this won’t be possible, as I haven’t seen any APIs anywhere that can push new settings to the inverter, but thought I’d ask!
I have my DC battery set to discharge only during certain times.  At night when I charge my EVs, the battery is set to not discharge, as I don’t want to charge the EVs from the house battery.  I can change the settings using the SolaX app (after entering a four digit PIN).
It would be nice to be able to dynamically change the times the battery discharges through the Home app.  Even a “Dicharge / Not discharge” button that merely changes the discharge times on the inverter would be awesome.

Have you seen anything that would allow for this?

**Comment by troygNZ** [comment]
No I haven't seen anything, but if you ever do come across details of an API that allows this, send it through, and I'll see what i can do.

I modelled some of this plugin off of a Home Assistant extension, but didn't see anything about controlling the inverter - but a cool idea!
