### ISSUE TITLE
Request to include solax cloud api 

### ISSUE THREAD

**Issue by HeuerJan** [troygNZ/homebridge-solax#30]
Hi,

it would be great if solax cloud could also be used as a source as well.
A api is available:

https://www.eu.solaxcloud.com/phoebus/resource/files/userGuide/Solax_API_for_End-user_V1.0.pdf

**Comment by troygNZ** [comment]
That's a great idea @HeuerJan - for whatever reason, my inverter doesn't allow me to sign-up to the cloud version, as it doesn't accept my serial number of the WiFi dongle. So have no easy way to develop and test this. If you were able to provision me a read-only type token to access your data (if happy with that), I could see what I can do?

**Comment by HeuerJan** [comment]
Do you have no access to the following page?

![6B912894-C1B0-40E0-A46F-D5EE8BEBC5DF](https://user-images.githubusercontent.com/54939440/108713118-13fdd800-7518-11eb-8ce3-fdcf317e32c6.png)

**Comment by troygNZ** [comment]
Sadly no, as I can't create the account to get to that area. The demo account only shows the overview, and nothing else for me.

**Comment by HeuerJan** [comment]
How can I send this to you in a less public way?

**Comment by HeuerJan** [comment]
Here is the JSON output that I receive from the API ( SN are changed ) 

{"exception":"Query success!","result":{"inverterSN":"H3DE3443664742","sn":"SE3HDOZZEN","acpower":435.0,"yieldtoday":1.0,"yieldtotal":5.6,"feedinpower":-21.0,"feedinenergy":3.29,"consumeenergy":9.14,"feedinpowerM2":0.0,"soc":63.0,"peps1":0.0,"peps2":0.0,"peps3":0.0,"inverterType":"5","inverterStatus":"102","uploadTime":"2021-02-24 12:38:34"},"success":true}

**Comment by HeuerJan** [comment]
And this is the URL that you need to use to fetch the above JSON
The user would need to enter in the settings just the token and the inverter serial number. Both are available in the cloud. 

 https://www.eu.solaxcloud.com:9443/proxy/api/getRealtimeInfo.do?tokenId=<TOKEN String>&sn=< Inverter serial number>

That’s all I can provide. If it helps, I can test the hombridge plugin for you.

**Comment by troygNZ** [comment]
> And this is the URL that you need to use to fetch the above JSON
> The user would need to enter in the settings just the token and the inverter serial number. Both are available in the cloud.
> 
> https://www.eu.solaxcloud.com:9443/proxy/api/getRealtimeInfo.do?tokenId=&sn=< Inverter serial number>
> 
> That’s all I can provide. If it helps, I can test the hombridge plugin for you.

Thanks, the sample reply itself will go a long way for me. Will likely make a start in about 10 days time (busy time of year for me)

**Comment by HeuerJan** [comment]
Be advised, that people with battery may have two inverter.

**Comment by HeuerJan** [comment]
The API output has been changed: (they added :  batPower in/out and powerdc1 + powerdc2 ( solar cell output ) )

{"exception":"Query success!","result":{"inverterSN":"H3DE11111111111","sn":"SEXXXXXXXXXX","acpower":183.0,"yieldtoday":4.0,"yieldtotal":210.0,"feedinpower":-33.0,"feedinenergy":117.82,"consumeenergy":178.12,"feedinpowerM2":0.0,"soc":20.0,"peps1":0.0,"peps2":0.0,"peps3":0.0,"inverterType":"5","inverterStatus":"102","uploadTime":"2021-03-11 09:40:00","batPower":200.0,"powerdc1":242.0,"powerdc2":135.0},"success":true}

**Comment by troygNZ** [comment]
Thanks @HeuerJan . I haven’t had a chance to get my hands dirty with it yet, but thanks for the update, much appreciated.

**Comment by HeuerJan** [comment]
Any news? I would really appreciate a way to control for example our pool heater according to solax output. For this a adaption of your home bridge plug-in would be really appreciated. 

I have in the meantime created a iOS app that uses the same api to show the data as a alternative to the solax cloud app: if you like to check out [:](www.SolXView.de/en)

**Comment by troygNZ** [comment]
> Any news? I would really appreciate a way to control for example our pool heater according to solax output. For this a adaption of your home bridge plug-in would be really appreciated.
> 
> I have in the meantime created a iOS app that uses the same api to show the data as a alternative to the solax cloud app: if you like to check out [:](www.SolXView.de/en)

Hi, my apologies - it's definitely been on the forefront of my thoughts, but since the weekend I was planning on working on it, several things have changed in my life. It's still on my TODO list, but has fallen down my priority list. 

In the interim, you're welcome to fork off of it if keen, and can prioritise the time for review pull-requests. No biggie if not, it is something I'm wanting to get to.

**Comment by AllMightySauron** [comment]
> Hi,
> 
> it would be great if solax cloud could also be used as a source as well. A api is available:
> 
> https://www.eu.solaxcloud.com/phoebus/resource/files/userGuide/Solax_API_for_End-user_V1.0.pdf

Hi @HeuerJan , feel free to try my Solax Cloud API homebridge plugin at https://github.com/AllMightySauron/homebride-solaxcloud-api.
