### ISSUE TITLE
Only absolute URLs are supported

### ISSUE THREAD

**Issue by theduca** [troygNZ/homebridge-solax#39]
Hi Would like to start by saying that I'm new to Homebridge and have had some success with using it.

I really like the fact that there is a Solax plugin, as this will be a fantastic feature that i can add to my home setup.

i have installed the plugin, however I'm not seeing any updates and when i referred to the status log i can see an error message with the following :

"only absolute URL's are supported"

**Screenshots**
[10/01/2022, 8:59:02 am] [Solax Inverter] That did not go well. Error: TypeError: Only absolute URLs are supported
[10/01/2022, 8:59:02 am] [Solax Inverter] Failed to read from Solax. Error: TypeError: Only absolute URLs are supported

The current environment config is running

Node.js Version | v16.13.1
NPM | v8.1.2

I have tested the url  http://192.168.xxx.xxx/api/realTimeData.htm to confirm that the content is available. See below: (Note, i just removed the SN data)

{"method":"uploadsn","version":"Solax_SI_CH_2nd_20160912_DE02","type":"AL_SE","SN":"(I have removed)","Data":[0.8,0.8,379.1,193.3,-0.9,233.5,0,43,0.9,20314.2,-4939,303,154,49.86,9.26,462,26,16,0.1,3943.1,,,,,,,,,,,,,,,,,,,,,,0.00,0.00,,,,,,,,50.00,,,0.0,0.0,0,0.00,0,0,0,0.00,0,9,0,0,0.00,0,9],"Status":"2"}

if there is anything else that may help support the review of this issue, please let me know.

Cheers

Vinny

**Comment by troygNZ** [comment]
Hi Vinny,
Thanks for taking the time to try it out.
For your configuration, what is your Inverter Address set to?

For the address, it should just be IP address with no trailing slash etc.
E.g. ` http://192.168.xxx.xxx` 

Hopefully that's all it is.

**Comment by theduca** [comment]
Hi TroygNZ

Silly me, i did not include "http://", i only had in the IP address.

now that i have entered it in the correct format "http://192.168.xxx.xxx" - it works "yay!!" 

thanks mate, fantastic plug in.

I have not played around, but im wondering, can this support more than 1 inverter at a time?

**Comment by troygNZ** [comment]
Ah that's good to hear.
Ideally there should be validation on the config form, ensuring a well-formed URL. But I had to remove some of it due to a bug/change in behavior in the homebridge validation for hostnames. But I could look at adding regex based validation in future.

At the moment it won't support more than one inverter sorry. In an ideal world if it did support multiple inverters, would it surface the values as sums across all the inverters, or surface them individually, or combination of both approaches?

**Comment by theduca** [comment]
the system that i have comprises of a 2 x 5kw inverters and i refer to it as a whole system. So a sum across all inverters would be fantastic. (i could also see benefits for scenario's that would be a combination of individual and combined).

cheers

**Comment by troygNZ** [comment]
Good to know, cheers. 
I can't promise anything, but may look at knocking something up.

In the interim,  if the inverters are setup with similar orientation (e.g. All west facing). you could make decisions based on the one inverter, to crudely extrapolate out. Well for total produced anways.
For example, if Inverter 1 was ~5kw, western facing, and Inverter 2 was 4kw western facing. If Inverter 1 is producing 2.5kw, then you could probably assume Inverter 2 is producing ~2kw.

Though for how power export or consumption is divied up, I'm not sure how multiple inverters work.. Does consumption across the house get shared evenly, or proportionally between the two, or is one consumed to it's entirity on one unit before it starts to consume the other inverters excess for example. But based on your observations using the Solax Portal, you may be able to work out how it's done, and extrapolate out still, to make some smart decisions.
